# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - door_opening_mechanism_joint_y_axis_slide
      - door_opening_mechanism_joint_x_axis_slide
      - door_opening_mechanism_joint_rotating_arm
      - door_opening_mechanism_joint_freely_rotating_hook