# Full set of configurations
- ros_topic_name: "tf"
  gz_topic_name: "/model/rb_theron/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: BIDIRECTIONAL      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Ignition topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Ignition

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/6OG/model/rb_theron/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: BIDIRECTIONAL

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/6OG/model/door_opening_mechanism/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: BIDIRECTIONAL                          


- ros_topic_name: "/front_laser/scan"
  gz_topic_name: "/front_laser/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/bpearl_laser/scan/points"
  gz_topic_name: "/bpearl_laser/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_realsense_camera/color"
  gz_topic_name: "/front_realsense_camera/color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_realsense_camera/depth"
  gz_topic_name: "/front_realsense_camera/front_realsense_camera/depth"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_realsense_camera/depth/points"
  gz_topic_name: "/front_realsense_camera/front_realsense_camera/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_oak_d_camera/color"
  gz_topic_name: "/back_top_oak_d_camera/color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_oak_d_camera/depth"
  gz_topic_name: "/back_top_oak_d_camera/back_top_oak_d_camera/depth"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_oak_d_camera/depth/points"
  gz_topic_name: "/back_top_oak_d_camera/back_top_oak_d_camera/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_top_oak_d_camera/color"
  gz_topic_name: "/front_top_oak_d_camera/color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_top_oak_d_camera/depth"
  gz_topic_name: "/front_top_oak_d_camera/front_top_oak_d_camera/depth"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/front_top_oak_d_camera/depth/points"
  gz_topic_name: "/front_top_oak_d_camera/front_top_oak_d_camera/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_realsense_camera/color"
  gz_topic_name: "/back_top_realsense_camera/color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_realsense_camera/depth"
  gz_topic_name: "/back_top_realsense_camera/back_top_realsense_camera/depth"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_top_realsense_camera/depth/points"
  gz_topic_name: "/back_top_realsense_camera/back_top_realsense_camera/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_realsense_camera/color"
  gz_topic_name: "/back_realsense_camera/color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_realsense_camera/depth"
  gz_topic_name: "/back_realsense_camera/back_realsense_camera/depth"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/back_realsense_camera/depth/points"
  gz_topic_name: "/back_realsense_camera/back_realsense_camera/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/odom"
  gz_topic_name: "/model/rb_theron/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: ROS_TO_GZ

- ros_topic_name: "/imu/data"
  gz_topic_name: "/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  subscriber_queue: 10      # Default 10
  publisher_queue: 10       # Default 10
  lazy: true               # Default "false"
  direction: GZ_TO_ROS
