<?xml version="1.0"?>
<robot name="drawer" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="box_inertia_robot" params="m x y z">
        <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
                iyy="${m*(x*x+z*z)/12}" iyz = "0"
                izz="${m*(x*x+y*y)/12}" />
    </xacro:macro>

    <xacro:property name="drawer_size_x" value="0.45" />
    <xacro:property name="drawer_size_y" value="0.358" />
    <!-- Mass should actually not be that small, but there is an issue, that if there is too much load on the theron base,
      it would be able to drive properly, because this makes some of the wheels lose contact to the ground and 
      therefore steering of the rb_theron becomes impossible -->
    <xacro:property name="drawer_mass" value="1.0" />

    <xacro:property name="drawer_offset_x" value="0.0" />
    <xacro:property name="drawer_offset_y" value="0.0" />
    <xacro:property name="drawer_offset_z" value="0.0" />


    <xacro:macro name="drawer" params="prefix suffix parent *origin ros2_control_hardware_type ros_distro drawer_size_z">
        <link name="${prefix}drawer_${suffix}">
            <inertial>
                <mass value="${drawer_mass}" />
                <origin xyz="${drawer_offset_x} ${drawer_offset_y} ${drawer_offset_z}" />
                <xacro:box_inertia_robot m="${drawer_mass}" x="${drawer_size_x}" y="${drawer_size_y}" z="${drawer_size_z}"/>
            </inertial>
            <visual>
                <!-- visual origin is defined w.r.t. link local coordinate system -->
                <origin xyz="${drawer_offset_x} ${drawer_offset_y} ${drawer_offset_z}" rpy="0 0 0" />
                <geometry>
                    <box size="${drawer_size_x} ${drawer_size_y} ${drawer_size_z}" />
                </geometry>
            </visual>
            <collision>
                <!-- collision origin is defined w.r.t. link local coordinate system -->
                <origin xyz="${drawer_offset_x} ${drawer_offset_y} ${drawer_offset_z}" rpy="0 0 0 " />
                <geometry>
                        <box size="${drawer_size_x} ${drawer_size_y} ${drawer_size_z}" />
                </geometry>
        </collision>
        </link>

        <gazebo reference="${prefix}drawer_${suffix}">
                <material>Gazebo/White</material>
                <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <joint name="${prefix}drawer_${suffix}_joint" type="prismatic" >
            <axis xyz="1 0 0" />
            <parent link="${parent}" />
            <child link="${prefix}drawer_${suffix}" />
            <xacro:insert_block name="origin" />
            <limit lower="-0.01" upper="${0.95*drawer_size_y}" effort="1000" velocity="100" />
        </joint>

        <ros2_control name="${prefix}drawer_${suffix}_ros2_control" type="system">
            <hardware>

                <xacro:if value="${ros2_control_hardware_type == 'mock_components'}">
                    <plugin>mock_components/GenericSystem</plugin>
                    <param name="calculate_dynamics">true</param>
                </xacro:if>

                <xacro:if value="${ros2_control_hardware_type == 'gz_ros2_control'}">
                    <xacro:if value="${ros_distro == 'humble'}">
                        <plugin>ign_ros2_control/IgnitionSystem</plugin>
                    </xacro:if>
                    <xacro:unless value="${ros_distro == 'humble'}">
                        <plugin>gz_ros2_control/GazeboSimSystem</plugin>
                    </xacro:unless>
                </xacro:if>

                <xacro:if value="${ros2_control_hardware_type == 'dryve_d1'}">
                    <plugin>mock_components/GenericSystem</plugin>
                    <param name="calculate_dynamics">true</param>
                </xacro:if>

            </hardware>
            <joint name="${prefix}drawer_${suffix}_joint">
                <command_interface name="position">
                    <param name="min">-0.01</param>
                    <param name="max">${0.95*drawer_size_y}</param>
                </command_interface>
                <state_interface name="position"/>
                <state_interface name="velocity"/>
            </joint>
        </ros2_control>

    </xacro:macro>

</robot>