<?xml version="1.0"?>
<robot name="sensor_r430" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:property name="M_PI" value="3.1415926535897931" />

  <!-- The following values are approximate, and the camera node
   publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="r430_cam_depth_to_left_ir_offset" value="-0.021"/>
    <xacro:property name="r430_cam_depth_to_right_ir_offset" value="0.029"/>
  <xacro:property name="r430_cam_depth_to_fisheye_offset" value="0.044"/>

  <!-- The following values model the aluminum peripherial case for the
    R430 camera, with the camera joint represented by the actual
    peripherial camera tripod mount -->
  <xacro:property name="r430_cam_width" value="0.100"/>
  <xacro:property name="r430_cam_depth" value="0.025"/>
  <xacro:property name="r430_cam_height" value="0.025"/>
  <xacro:property name="r430_cam_mount_from_center_offset" value="0.0"/>

  <!-- The following offset is relative the the physical R430 camera peripherial
    camera tripod mount -->
  <xacro:property name="r430_cam_depth_px" value="0.00"/>
  <xacro:property name="r430_cam_depth_py" value="-0.0115"/>
  <xacro:property name="r430_cam_depth_pz" value="0.0"/>

  <xacro:macro name="sensor_r430" params="prefix parent publish_bf robot_name prefix_topic:='front_rgbd_camera' hq *origin">

    <xacro:if value="${publish_bf}">
			<xacro:property name="sensor_link_name" value="${robot_name}/base_footprint/${prefix}" />
		</xacro:if>
		<xacro:unless value="${publish_bf}">
			<xacro:property name="sensor_link_name" value="${robot_name}/base_link/${prefix}" />
		</xacro:unless>

    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${prefix}_camera_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}_link" />
    </joint>

    <link name="${prefix}_link">
      <visual>
        <!-- origin xyz="0 ${-r430_cam_mount_from_center_offset} ${r430_cam_height/2}" rpy="${M_PI/2} 0 ${M_PI/2}"/ -->
        <origin xyz="0 ${-r430_cam_mount_from_center_offset} 0" rpy="0 0 0"/>
        <geometry>
          <xacro:if value="${hq}">
            <mesh filename="$(find robotnik_sensors)/meshes/intel_r430.dae" />
          </xacro:if>
          <xacro:unless value="${hq}">
            <box size="${r430_cam_depth} ${r430_cam_width} ${r430_cam_height} "/>
          </xacro:unless>
        </geometry>
        <material name="aluminum">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 ${-r430_cam_mount_from_center_offset} 0" rpy="0 0 0"/>
        <geometry>
        <box size="${r430_cam_depth} ${r430_cam_width} ${r430_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="-0.0125 0.0 0.0" rpy="0 0 0" />
        <mass value="0.1" />
        <xacro:solid_cuboid_inertia m="0.1" w="0.025" h="0.09" d="0.025" />
      </inertial>
    </link>

    <!-- camera depth joints and links -->
    <joint name="${prefix}_camera_depth_joint" type="fixed">
      <origin xyz="${r430_cam_depth_px} ${r430_cam_depth_py} ${r430_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="${prefix}_link"/>
      <child link="${prefix}_camera_depth_frame" />
    </joint>
    <link name="${prefix}_camera_depth_frame"/>
    
    <joint name="${prefix}_camera_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${prefix}_camera_depth_frame" />
      <child link="${sensor_link_name}_depth_link" />
    </joint>
    <link name="${sensor_link_name}_depth_link"/>

    <joint name="${prefix}_camera_color_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}_camera_depth_frame" />
      <child link="${sensor_link_name}_color_link" />
    </joint>
    <link name="${sensor_link_name}_color_link"/>

    <!-- camera left IR joints and links -->
    <joint name="${prefix}_camera_left_ir_joint" type="fixed">
      <origin xyz="0 ${r430_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
      <parent link="${prefix}_camera_depth_frame" />
      <child link="${prefix}_camera_left_ir_frame" />
    </joint>
    <link name="${prefix}_camera_left_ir_frame"/>

    <joint name="${prefix}_camera_left_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}_camera_left_ir_frame" />
      <child link="${prefix}_camera_left_ir_optical_frame" />
    </joint>
    <link name="${prefix}_camera_left_ir_optical_frame"/>

    <!-- camera right IR joints and links -->
    <joint name="${prefix}_camera_right_ir_joint" type="fixed">
      <origin xyz="0 ${r430_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
      <parent link="${prefix}_camera_depth_frame" />
      <child link="${prefix}_camera_right_ir_frame" />
    </joint>
    <link name="${prefix}_camera_right_ir_frame"/>

    <joint name="${prefix}_camera_right_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}_camera_right_ir_frame" />
      <child link="${prefix}_camera_right_ir_optical_frame" />
    </joint>
    <link name="${prefix}_camera_right_ir_optical_frame"/>

    <!-- camera fisheye joints and links -->
    <joint name="${prefix}_camera_fisheye_joint" type="fixed">
      <origin xyz="0 ${r430_cam_depth_to_fisheye_offset} 0" rpy="0 0 0" />
      <parent link="${prefix}_camera_depth_frame" />
      <child link="${prefix}_camera_fisheye_frame" />
    </joint>
    <link name="${prefix}_camera_fisheye_frame"/>

    <joint name="${prefix}_camera_fisheye_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}_camera_fisheye_frame" />
      <child link="${prefix}_camera_fisheye_optical_frame" />
    </joint>
    <link name="${prefix}_camera_fisheye_optical_frame"/>

    <!-- RGBD sensor for simulation, same as Kinect -->
    <xacro:sensor_r430_gazebo/>
  </xacro:macro>

  <xacro:macro name="sensor_r430_gazebo">

    <!-- gazebo reference="${prefix}_rgb_base_link" -->
    <gazebo reference="${prefix}_link">
      <sensor name="${prefix}_color_link" type="camera">
				<topic>${prefix_topic}/color</topic>
        <camera name="r430">
            <horizontal_fov>1.2112585008840648</horizontal_fov>
            <image>
                <width>640</width>
                <height>480</height>
                <format>RGB_INT8</format>
            </image>
            <clip>
                <near>0.1</near>
                <far>100</far>
            </clip>
              <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.007</stddev>
            </noise>
        </camera>
        
        <always_on>1</always_on>
        <update_rate>30</update_rate>
        <visualize>1</visualize>
      </sensor>
      
      <sensor name="${prefix}_ired1" type="camera">
      <topic>${prefix_topic}/${prefix}/ired1</topic>
        <camera name="r430">
          <horizontal_fov>${91.2*M_PI/180.0}</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>L_INT8</format>
          </image>
          <clip>
            <near>0.3</near>
            <far>10.0</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.05</stddev>
          </noise>
        </camera>
        <always_on>1</always_on>
        <update_rate>90</update_rate>
        <visualize>0</visualize>
      </sensor>

      <sensor name="${prefix}_ired2" type="camera">
        <topic>${prefix_topic}/${prefix}/ired2</topic>
        <camera name="r430">
          <horizontal_fov>1.4870205226991688</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>L_INT8</format>
          </image>
          <clip>
            <near>0.3</near>
            <far>10.0</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.05</stddev>
          </noise>
        </camera>
        <always_on>1</always_on>
        <update_rate>90</update_rate>
        <visualize>0</visualize>
      </sensor>

      <sensor name="${prefix}_depth_link" type="depth">
        <topic>${prefix_topic}/${prefix}/depth</topic>
        <camera name="r430">
          <horizontal_fov>${91.2*M_PI/180.0}</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
          </image>
          <clip>
            <near>0.3</near>
            <far>10.0</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.010</stddev>
          </noise>
        </camera>
        <always_on>1</always_on>
        <update_rate>15</update_rate>
        <visualize>1</visualize>
      </sensor>
    </gazebo>  
  </xacro:macro>


</robot>
